<?php

namespace ContainerU9cv0Dv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JT9Zhf5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JT9Zhf5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JT9Zhf5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.JT9Zhf5.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.JT9Zhf5": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'sourcesRepository' => ['privates', 'App\\Repository\\SourcesRepository', 'getSourcesRepositoryService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'sourcesRepository' => 'App\\Repository\\SourcesRepository',
        ]);
    }
}
