<?php

namespace ContainerU9cv0Dv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NGuS5cdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NGuS5cd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NGuS5cd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'source' => ['privates', '.errored..service_locator.NGuS5cd.App\\Entity\\Sources', NULL, 'Cannot autowire service ".service_locator.NGuS5cd": it needs an instance of "App\\Entity\\Sources" but this type has been excluded in "config/services.yaml".'],
        ], [
            'source' => 'App\\Entity\\Sources',
        ]);
    }
}
