<?php

namespace ContainerU9cv0Dv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSources2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QeJMtgY.App\Entity\Sources' shared service.
     *
     * @return \App\Entity\Sources
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QeJMtgY": it needs an instance of "App\\Entity\\Sources" but this type has been excluded in "config/services.yaml".');
    }
}
