<?php

namespace ContainerX7dAN4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HVhu5IzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hVhu5Iz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hVhu5Iz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LanguageController::delete' => ['privates', '.service_locator.O0VupqY', 'get_ServiceLocator_O0VupqYService', true],
            'App\\Controller\\LanguageController::edit' => ['privates', '.service_locator.O0VupqY', 'get_ServiceLocator_O0VupqYService', true],
            'App\\Controller\\LanguageController::index' => ['privates', '.service_locator.QgQ8wqG', 'get_ServiceLocator_QgQ8wqGService', true],
            'App\\Controller\\LanguageController::new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\LanguageController::show' => ['privates', '.service_locator.0aVz0s0', 'get_ServiceLocator_0aVz0s0Service', true],
            'App\\Controller\\ProjectController::delete' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\ProjectController::edit' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\ProjectController::index' => ['privates', '.service_locator.HpX8TON', 'get_ServiceLocator_HpX8TONService', true],
            'App\\Controller\\ProjectController::new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.1.2RqhU', 'get_ServiceLocator_1_2RqhUService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SourcesController::delete' => ['privates', '.service_locator.QeJMtgY', 'get_ServiceLocator_QeJMtgYService', true],
            'App\\Controller\\SourcesController::edit' => ['privates', '.service_locator.QeJMtgY', 'get_ServiceLocator_QeJMtgYService', true],
            'App\\Controller\\SourcesController::index' => ['privates', '.service_locator.JT9Zhf5', 'get_ServiceLocator_JT9Zhf5Service', true],
            'App\\Controller\\SourcesController::new' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\SourcesController::show' => ['privates', '.service_locator.NGuS5cd', 'get_ServiceLocator_NGuS5cdService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.VNXcd7p', 'get_ServiceLocator_VNXcd7pService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LanguageController:delete' => ['privates', '.service_locator.O0VupqY', 'get_ServiceLocator_O0VupqYService', true],
            'App\\Controller\\LanguageController:edit' => ['privates', '.service_locator.O0VupqY', 'get_ServiceLocator_O0VupqYService', true],
            'App\\Controller\\LanguageController:index' => ['privates', '.service_locator.QgQ8wqG', 'get_ServiceLocator_QgQ8wqGService', true],
            'App\\Controller\\LanguageController:new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\LanguageController:show' => ['privates', '.service_locator.0aVz0s0', 'get_ServiceLocator_0aVz0s0Service', true],
            'App\\Controller\\ProjectController:delete' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\ProjectController:edit' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\ProjectController:index' => ['privates', '.service_locator.HpX8TON', 'get_ServiceLocator_HpX8TONService', true],
            'App\\Controller\\ProjectController:new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.1.2RqhU', 'get_ServiceLocator_1_2RqhUService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SourcesController:delete' => ['privates', '.service_locator.QeJMtgY', 'get_ServiceLocator_QeJMtgYService', true],
            'App\\Controller\\SourcesController:edit' => ['privates', '.service_locator.QeJMtgY', 'get_ServiceLocator_QeJMtgYService', true],
            'App\\Controller\\SourcesController:index' => ['privates', '.service_locator.JT9Zhf5', 'get_ServiceLocator_JT9Zhf5Service', true],
            'App\\Controller\\SourcesController:new' => ['privates', '.service_locator.65Ejjb1', 'get_ServiceLocator_65Ejjb1Service', true],
            'App\\Controller\\SourcesController:show' => ['privates', '.service_locator.NGuS5cd', 'get_ServiceLocator_NGuS5cdService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.VNXcd7p', 'get_ServiceLocator_VNXcd7pService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LanguageController::delete' => '?',
            'App\\Controller\\LanguageController::edit' => '?',
            'App\\Controller\\LanguageController::index' => '?',
            'App\\Controller\\LanguageController::new' => '?',
            'App\\Controller\\LanguageController::show' => '?',
            'App\\Controller\\ProjectController::delete' => '?',
            'App\\Controller\\ProjectController::edit' => '?',
            'App\\Controller\\ProjectController::index' => '?',
            'App\\Controller\\ProjectController::new' => '?',
            'App\\Controller\\ProjectController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SourcesController::delete' => '?',
            'App\\Controller\\SourcesController::edit' => '?',
            'App\\Controller\\SourcesController::index' => '?',
            'App\\Controller\\SourcesController::new' => '?',
            'App\\Controller\\SourcesController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LanguageController:delete' => '?',
            'App\\Controller\\LanguageController:edit' => '?',
            'App\\Controller\\LanguageController:index' => '?',
            'App\\Controller\\LanguageController:new' => '?',
            'App\\Controller\\LanguageController:show' => '?',
            'App\\Controller\\ProjectController:delete' => '?',
            'App\\Controller\\ProjectController:edit' => '?',
            'App\\Controller\\ProjectController:index' => '?',
            'App\\Controller\\ProjectController:new' => '?',
            'App\\Controller\\ProjectController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SourcesController:delete' => '?',
            'App\\Controller\\SourcesController:edit' => '?',
            'App\\Controller\\SourcesController:index' => '?',
            'App\\Controller\\SourcesController:new' => '?',
            'App\\Controller\\SourcesController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
